# Generated by Django 5.2 on 2025-05-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='name',
        ),
    ]
