# Generated by Django 5.2.1 on 2025-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(default=1, upload_to='articles/headers/'),
            preserve_default=False,
        ),
    ]
