# Generated by Django 5.1.7 on 2025-03-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Category',
            new_name='ArticleCategory',
        ),
    ]
